SPLITWISE_API_KEY: HNyMKq3G276RkvLVGzMskeMSxdGDHDw52mTMN19q
SPLITWISE_API_SECRET: 7OAgSeE5ELVRLSpJJIvCLN8skLFlJuN96lDI7b5K
SPLITWISE_SITE: "https://secure.splitwise.com"
SPLITWISE_AUTHORIZE_URL: "/authorize"
SPLITWISE_REQUEST_TOKEN_URL: "/api/v3.0/get_request_token"
SPLITWISE_ACCESS_TOKEN_URL: "/api/v3.0/get_access_token"

